[package]
name = "ecc608-linux"
version = "0.1.0"
authors = ["Marc Nijdam <marc@helium.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
i2c-linux = "0"
sha2 = "0"
bytes = "1"
bitfield = "0"
serde = "1"
serde_derive = "1"
thiserror = "1"
